name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Clang Build
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        # C Compiler for toolchain
        cc: clang # optional
        # C++ Compiler for toolchain
        cxx: clang++ # optional
        update-submodules: true
        parallel: 8
        build-dir: ${{runner.workspace}}/build-clang 
    - name: gcc Build
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        # C Compiler for toolchain
        cc: gcc # optional
        # C++ Compiler for toolchain
        cxx: g++ # optional
        update-submodules: true
        parallel: 8
        build-dir: ${{runner.workspace}}/build-gcc
